--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: diffuse; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.diffuse (
    matchid integer,
    roundnumber integer,
    eventlocation text,
    eventtime timestamp without time zone,
    diffuser character varying(100)
);


ALTER TABLE public.diffuse OWNER TO postgres;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: elimination; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.elimination (
    matchid integer,
    roundnumber integer,
    eventlocation text,
    eventtime timestamp without time zone,
    playereliminating character varying(100),
    playereliminated character varying(100),
    assistingplayers text
);


ALTER TABLE public.elimination OWNER TO postgres;

--
-- Name: matches; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matches (
    matchid integer NOT NULL,
    tournamentname character varying(100),
    date date,
    team1 character varying(80),
    team2 character varying(80)
);


ALTER TABLE public.matches OWNER TO postgres;

--
-- Name: matches_matchid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.matches_matchid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.matches_matchid_seq OWNER TO postgres;

--
-- Name: matches_matchid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.matches_matchid_seq OWNED BY public.matches.matchid;


--
-- Name: plant; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.plant (
    matchid integer,
    roundnumber integer,
    eventlocation text,
    eventtime timestamp without time zone,
    planter character varying(100)
);


ALTER TABLE public.plant OWNER TO postgres;

--
-- Name: players; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.players (
    playername character varying(100) NOT NULL,
    teamname character varying(100)
);


ALTER TABLE public.players OWNER TO postgres;

--
-- Name: playersocialmedia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.playersocialmedia (
    playername character varying(100),
    socialmedialink text
);


ALTER TABLE public.playersocialmedia OWNER TO postgres;

--
-- Name: playin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.playin (
    teamname character varying(100),
    playername character varying(100),
    tournamentname character varying(100)
);


ALTER TABLE public.playin OWNER TO postgres;

--
-- Name: rounds; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rounds (
    matchid integer NOT NULL,
    roundnumber integer NOT NULL,
    roundendtime timestamp without time zone,
    roundwinner character varying(100)
);


ALTER TABLE public.rounds OWNER TO postgres;

--
-- Name: teams; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teams (
    teamname character varying(100) NOT NULL
);


ALTER TABLE public.teams OWNER TO postgres;

--
-- Name: teamsocialmedia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teamsocialmedia (
    teamname character varying(100),
    socialmedialink text
);


ALTER TABLE public.teamsocialmedia OWNER TO postgres;

--
-- Name: tournaments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tournaments (
    name character varying(100) NOT NULL,
    daterange character varying(100),
    prestige integer,
    location text
);


ALTER TABLE public.tournaments OWNER TO postgres;

--
-- Name: valorantDatabase_playermatchrating; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."valorantDatabase_playermatchrating" (
    id bigint NOT NULL,
    rating double precision NOT NULL,
    match_id integer NOT NULL,
    player_id character varying(100) NOT NULL
);


ALTER TABLE public."valorantDatabase_playermatchrating" OWNER TO postgres;

--
-- Name: valorantDatabase_playermatchrating_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."valorantDatabase_playermatchrating" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."valorantDatabase_playermatchrating_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matches matchid; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches ALTER COLUMN matchid SET DEFAULT nextval('public.matches_matchid_seq'::regclass);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add auth group	10	add_authgroup
26	Can change auth group	10	change_authgroup
27	Can delete auth group	10	delete_authgroup
28	Can view auth group	10	view_authgroup
29	Can add auth group permissions	11	add_authgrouppermissions
30	Can change auth group permissions	11	change_authgrouppermissions
31	Can delete auth group permissions	11	delete_authgrouppermissions
32	Can view auth group permissions	11	view_authgrouppermissions
33	Can add auth permission	12	add_authpermission
34	Can change auth permission	12	change_authpermission
35	Can delete auth permission	12	delete_authpermission
36	Can view auth permission	12	view_authpermission
37	Can add auth user	13	add_authuser
38	Can change auth user	13	change_authuser
39	Can delete auth user	13	delete_authuser
40	Can view auth user	13	view_authuser
41	Can add auth user groups	14	add_authusergroups
42	Can change auth user groups	14	change_authusergroups
43	Can delete auth user groups	14	delete_authusergroups
44	Can view auth user groups	14	view_authusergroups
45	Can add auth user user permissions	15	add_authuseruserpermissions
46	Can change auth user user permissions	15	change_authuseruserpermissions
47	Can delete auth user user permissions	15	delete_authuseruserpermissions
48	Can view auth user user permissions	15	view_authuseruserpermissions
49	Can add diffuse	16	add_diffuse
50	Can change diffuse	16	change_diffuse
51	Can delete diffuse	16	delete_diffuse
52	Can view diffuse	16	view_diffuse
53	Can add django admin log	17	add_djangoadminlog
54	Can change django admin log	17	change_djangoadminlog
55	Can delete django admin log	17	delete_djangoadminlog
56	Can view django admin log	17	view_djangoadminlog
57	Can add django content type	18	add_djangocontenttype
58	Can change django content type	18	change_djangocontenttype
59	Can delete django content type	18	delete_djangocontenttype
60	Can view django content type	18	view_djangocontenttype
61	Can add django migrations	19	add_djangomigrations
62	Can change django migrations	19	change_djangomigrations
63	Can delete django migrations	19	delete_djangomigrations
64	Can view django migrations	19	view_djangomigrations
65	Can add django session	20	add_djangosession
66	Can change django session	20	change_djangosession
67	Can delete django session	20	delete_djangosession
68	Can view django session	20	view_djangosession
69	Can add elimination	21	add_elimination
70	Can change elimination	21	change_elimination
71	Can delete elimination	21	delete_elimination
72	Can view elimination	21	view_elimination
73	Can add plant	22	add_plant
74	Can change plant	22	change_plant
75	Can delete plant	22	delete_plant
76	Can view plant	22	view_plant
77	Can add playersocialmedia	23	add_playersocialmedia
78	Can change playersocialmedia	23	change_playersocialmedia
79	Can delete playersocialmedia	23	delete_playersocialmedia
80	Can view playersocialmedia	23	view_playersocialmedia
81	Can add playin	24	add_playin
82	Can change playin	24	change_playin
83	Can delete playin	24	delete_playin
84	Can view playin	24	view_playin
85	Can add teamsocialmedia	25	add_teamsocialmedia
86	Can change teamsocialmedia	25	change_teamsocialmedia
87	Can delete teamsocialmedia	25	delete_teamsocialmedia
88	Can view teamsocialmedia	25	view_teamsocialmedia
89	Can add round	26	add_round
90	Can change round	26	change_round
91	Can delete round	26	delete_round
92	Can view round	26	view_round
93	Can add match	27	add_match
94	Can change match	27	change_match
95	Can delete match	27	delete_match
96	Can view match	27	view_match
97	Can add tournament	28	add_tournament
98	Can change tournament	28	change_tournament
99	Can delete tournament	28	delete_tournament
100	Can view tournament	28	view_tournament
101	Can add player match rating	29	add_playermatchrating
102	Can change player match rating	29	change_playermatchrating
103	Can delete player match rating	29	delete_playermatchrating
104	Can view player match rating	29	view_playermatchrating
105	Can add player	7	add_player
106	Can change player	7	change_player
107	Can delete player	7	delete_player
108	Can view player	7	view_player
109	Can add team	9	add_team
110	Can change team	9	change_team
111	Can delete team	9	delete_team
112	Can view team	9	view_team
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1000000$V3BtrtxOiDJUGpbvICr1B4$GsjpqS4ZchMWJd8eMfBQfQUaouTq4+yy6hNBfyEEKZc=	2025-05-01 14:32:35.471249-05	t	admin			amoghrai06@gmail.com	t	t	2025-05-01 14:31:01.787787-05
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: diffuse; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.diffuse (matchid, roundnumber, eventlocation, eventtime, diffuser) FROM stdin;
1	1	Site A	2025-03-15 12:10:00	crashies
1	2	Site A	2025-03-15 12:20:00	Sacy
2	1	Site A	2025-03-16 12:10:00	Ethan
2	2	Site A	2025-03-16 12:20:00	Mazino
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	valorantDatabase	player
8	valorantDatabase	matches
9	valorantDatabase	team
10	valorantDatabase	authgroup
11	valorantDatabase	authgrouppermissions
12	valorantDatabase	authpermission
13	valorantDatabase	authuser
14	valorantDatabase	authusergroups
15	valorantDatabase	authuseruserpermissions
16	valorantDatabase	diffuse
17	valorantDatabase	djangoadminlog
18	valorantDatabase	djangocontenttype
19	valorantDatabase	djangomigrations
20	valorantDatabase	djangosession
21	valorantDatabase	elimination
22	valorantDatabase	plant
23	valorantDatabase	playersocialmedia
24	valorantDatabase	playin
25	valorantDatabase	teamsocialmedia
26	valorantDatabase	round
27	valorantDatabase	match
28	valorantDatabase	tournament
29	valorantDatabase	playermatchrating
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-04-30 23:40:45.90692-05
2	auth	0001_initial	2025-04-30 23:40:45.949643-05
3	admin	0001_initial	2025-04-30 23:40:45.963681-05
4	admin	0002_logentry_remove_auto_add	2025-04-30 23:40:45.968001-05
5	admin	0003_logentry_add_action_flag_choices	2025-04-30 23:40:45.972181-05
6	contenttypes	0002_remove_content_type_name	2025-04-30 23:40:45.980277-05
7	auth	0002_alter_permission_name_max_length	2025-04-30 23:40:45.984882-05
8	auth	0003_alter_user_email_max_length	2025-04-30 23:40:45.989255-05
9	auth	0004_alter_user_username_opts	2025-04-30 23:40:45.993076-05
10	auth	0005_alter_user_last_login_null	2025-04-30 23:40:45.997139-05
11	auth	0006_require_contenttypes_0002	2025-04-30 23:40:45.997997-05
12	auth	0007_alter_validators_add_error_messages	2025-04-30 23:40:46.001915-05
13	auth	0008_alter_user_username_max_length	2025-04-30 23:40:46.007755-05
14	auth	0009_alter_user_last_name_max_length	2025-04-30 23:40:46.011759-05
15	auth	0010_alter_group_name_max_length	2025-04-30 23:40:46.016335-05
16	auth	0011_update_proxy_permissions	2025-04-30 23:40:46.019681-05
17	auth	0012_alter_user_first_name_max_length	2025-04-30 23:40:46.023792-05
18	sessions	0001_initial	2025-04-30 23:40:46.02854-05
19	valorantDatabase	0001_initial	2025-05-02 17:11:54.662675-05
20	valorantDatabase	0002_playermatchrating	2025-05-02 17:16:15.271072-05
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
09ve46i9a3t9nw1dxvb06az8tf6d2mex	.eJxVjMsOwiAQRf-FtSFQGBhcuvcbCI9BqgaS0q6M_65NutDtPefcF_NhW6vfBi1-zuzMJDv9bjGkB7Ud5Htot85Tb-syR74r_KCDX3um5-Vw_w5qGPVbT5LQClXQQZmSNVEKKpkgoY2OQOuAwRWHKkkwEo0RCaLErIiAhFbs_QHZrTeM:1uAZe7:H5GWUR9Ln-OEInNX_JOwSllC_okzEdgLC8Pd6DhY2bk	2025-05-15 14:32:35.475023-05
\.


--
-- Data for Name: elimination; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.elimination (matchid, roundnumber, eventlocation, eventtime, playereliminating, playereliminated, assistingplayers) FROM stdin;
1	1	Mid	2025-03-15 12:09:15	TenZ	aspas	Sacy
1	2	Mid	2025-03-15 12:19:15	Less	pANcada	qck
2	1	Mid	2025-03-16 12:09:15	FNS	Shyy	Ethan
2	2	Mid	2025-03-16 12:19:15	keznit	FNS	Mazino
\.


--
-- Data for Name: matches; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.matches (matchid, tournamentname, date, team1, team2) FROM stdin;
1	VCT Americas Stage One 2025	2025-03-15	Sentinels	LOUD
2	VCT Americas Stage One 2025	2025-03-16	LOUD	NRG
3	VCT Americas Stage One 2025	2025-03-17	NRG	Leviatán
4	VCT Americas Stage One 2025	2025-03-18	Leviatán	Sentinels
5	VCT Americas Stage One 2025	2025-03-19	Sentinels	LOUD
6	VCT Americas Stage One 2025	2025-03-20	LOUD	NRG
7	VCT Americas Stage One 2025	2025-03-21	NRG	Leviatán
8	VCT Americas Stage One 2025	2025-03-22	Leviatán	Sentinels
9	VCT Americas Stage One 2025	2025-03-23	Sentinels	LOUD
10	VCT Americas Stage One 2025	2025-03-24	LOUD	NRG
11	VCT Americas Stage One 2025	2025-03-25	NRG	Leviatán
12	VCT Americas Stage One 2025	2025-03-26	Leviatán	Sentinels
13	VCT Americas Stage One 2025	2025-03-27	Sentinels	LOUD
14	VCT Americas Stage One 2025	2025-03-28	LOUD	NRG
15	VCT Americas Stage One 2025	2025-03-29	NRG	Leviatán
16	VCT Americas Stage One 2025	2025-03-30	Leviatán	Sentinels
17	VCT Americas Stage One 2025	2025-03-31	Sentinels	LOUD
18	VCT Americas Stage One 2025	2025-04-01	LOUD	NRG
19	VCT Americas Stage One 2025	2025-04-02	NRG	Leviatán
20	VCT Americas Stage One 2025	2025-04-03	Leviatán	Sentinels
\.


--
-- Data for Name: plant; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.plant (matchid, roundnumber, eventlocation, eventtime, planter) FROM stdin;
1	1	Site A	2025-03-15 12:09:00	TenZ
1	2	Site A	2025-03-15 12:19:00	Less
2	1	Site A	2025-03-16 12:09:00	FNS
2	2	Site A	2025-03-16 12:19:00	keznit
\.


--
-- Data for Name: players; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.players (playername, teamname) FROM stdin;
TenZ	Sentinels
Sacy	Sentinels
Zekken	Sentinels
pANcada	Sentinels
johnqt	Sentinels
aspas	LOUD
Less	LOUD
Saadhak	LOUD
Cauanzin	LOUD
qck	LOUD
demon1	NRG
crashies	NRG
Ethan	NRG
FNS	NRG
s0m	NRG
keznit	Leviatán
Mazino	Leviatán
Shyy	Leviatán
kiNgg	Leviatán
tex	Leviatán
\.


--
-- Data for Name: playersocialmedia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.playersocialmedia (playername, socialmedialink) FROM stdin;
\.


--
-- Data for Name: playin; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.playin (teamname, playername, tournamentname) FROM stdin;
\.


--
-- Data for Name: rounds; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rounds (matchid, roundnumber, roundendtime, roundwinner) FROM stdin;
1	1	2025-03-15 12:10:00	LOUD
1	2	2025-03-15 12:20:00	Sentinels
2	1	2025-03-16 12:10:00	NRG
2	2	2025-03-16 12:20:00	Leviatán
3	1	2025-03-17 12:10:00	Sentinels
3	2	2025-03-17 12:20:00	LOUD
4	1	2025-03-18 12:10:00	Leviatán
4	2	2025-03-18 12:20:00	NRG
5	1	2025-03-19 12:10:00	Sentinels
5	2	2025-03-19 12:20:00	LOUD
\.


--
-- Data for Name: teams; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.teams (teamname) FROM stdin;
Sentinels
LOUD
NRG
Leviatán
\.


--
-- Data for Name: teamsocialmedia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.teamsocialmedia (teamname, socialmedialink) FROM stdin;
\.


--
-- Data for Name: tournaments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tournaments (name, daterange, prestige, location) FROM stdin;
VCT Americas Stage One 2025	2025-03-15 to 2025-04-15	5	Los Angeles, USA
\.


--
-- Data for Name: valorantDatabase_playermatchrating; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."valorantDatabase_playermatchrating" (id, rating, match_id, player_id) FROM stdin;
1	1.39856552192134	1	TenZ
2	0.8572117040633838	1	Sacy
3	1.2273502704350996	1	Zekken
4	1.386560587747439	1	pANcada
5	1.1513899649430326	1	johnqt
6	1.1283238177525188	1	aspas
7	0.6832142462212641	1	Less
8	0.7606238407080153	1	Saadhak
9	1.3472433674961464	1	Cauanzin
10	0.1844781821686957	1	qck
11	1.146571717976271	2	aspas
12	0.6608250882795375	2	Less
13	0.43073475435050007	2	Saadhak
14	1.1801987239975529	2	Cauanzin
15	1.1519083181317171	2	qck
16	1.2759001261673522	2	demon1
17	1.1074982591364622	2	crashies
18	0.37487425661103224	2	Ethan
19	0.9464564194455191	2	FNS
20	1.30997661197231	2	s0m
21	1.3200217319617642	3	demon1
22	0.7914838499110096	3	crashies
23	0.8062323059242966	3	Ethan
24	1.2382919806827706	3	FNS
25	0.8970382478899498	3	s0m
26	0.28529910877724274	3	keznit
27	0.9789850987739972	3	Mazino
28	1.3899576768576836	3	Shyy
29	0.7988657201413853	3	kiNgg
30	1.1850875003206398	3	tex
31	0.7654970807123928	4	keznit
32	0.43584664399900386	4	Mazino
33	1.2579755485858597	4	Shyy
34	0.6597871693167328	4	kiNgg
35	0.6434957091784055	4	tex
36	1.0215387526747794	4	TenZ
37	0.5602231969541026	4	Sacy
38	0.903777961905702	4	Zekken
39	0.9819562863660835	4	pANcada
40	0.9099054865432221	4	johnqt
41	0.7068746629964258	5	TenZ
42	0.6474712255095492	5	Sacy
43	0.5281244817962154	5	Zekken
44	0.6293973726682509	5	pANcada
45	0.8155918356363955	5	johnqt
46	0.8978386406785904	5	aspas
47	0.8221160380794648	5	Less
48	0.9110681160676707	5	Saadhak
49	0.8460821866380779	5	Cauanzin
50	1.1594311879879877	5	qck
51	1.3122406028876699	6	aspas
52	1.3100460402490692	6	Less
53	0.47033022667804747	6	Saadhak
54	1.380707809747493	6	Cauanzin
55	1.3947598299752653	6	qck
56	1.1676944587908564	6	demon1
57	0.9529739214246365	6	crashies
58	0.47657147187536647	6	Ethan
59	1.1519825519777138	6	FNS
60	0.947805158093858	6	s0m
61	0.782030220948649	7	demon1
62	0.6599652601163252	7	crashies
63	1.062892695159715	7	Ethan
64	0.7240747362182339	7	FNS
65	1.1635346905228936	7	s0m
66	0.6512551530831616	7	keznit
67	1.1538935953990674	7	Mazino
68	1.0603886937726128	7	Shyy
69	1.0512420876050783	7	kiNgg
70	0.9034655516451853	7	tex
71	1.351303750405565	8	keznit
72	1.2087358769758811	8	Mazino
73	1.2059901370734163	8	Shyy
74	0.6843225340457164	8	kiNgg
75	1.2713589312005995	8	tex
76	0.6594470826918826	8	TenZ
77	1.1068792776951806	8	Sacy
78	0.9915652122489612	8	Zekken
79	0.9578596029668531	8	pANcada
80	1.2946280060308077	8	johnqt
81	0.7597843689821607	9	TenZ
82	0.49829230214359793	9	Sacy
83	1.0767533248865693	9	Zekken
84	0.2047297752822307	9	pANcada
85	0.9721795692609579	9	johnqt
86	0.8923199301331823	9	aspas
87	0.9273075859980118	9	Less
88	1.2670150841924166	9	Saadhak
89	1.0943219647732716	9	Cauanzin
90	1.1553705155675882	9	qck
91	1.3193498228947098	10	aspas
92	1.1643713466404466	10	Less
93	0.7098083849018721	10	Saadhak
94	1.2616790057402694	10	Cauanzin
95	0.9445639694778422	10	qck
96	0.709752533098157	10	demon1
97	1.3808508594663236	10	crashies
98	1.0144182214340858	10	Ethan
99	1.00559065848615	10	FNS
100	1.077027111620993	10	s0m
101	1.089530208118759	11	demon1
102	1.0891343895624905	11	crashies
103	1.128157837942856	11	Ethan
104	0.5116701358623906	11	FNS
105	0.9219792420868899	11	s0m
106	0.7278547250965374	11	keznit
107	1.1234686847625954	11	Mazino
108	1.3245654021836837	11	Shyy
109	1.3725121728530438	11	kiNgg
110	0.5484810916494892	11	tex
111	1.2446617701330598	12	keznit
112	1.3873890849504018	12	Mazino
113	1.3508204831131303	12	Shyy
114	1.077256697933208	12	kiNgg
115	0.9699448020348429	12	tex
116	0.9145327846390318	12	TenZ
117	1.0932003356491595	12	Sacy
118	1.2354682945729727	12	Zekken
119	1.2309014511004328	12	pANcada
120	0.9326620132082525	12	johnqt
121	0.906709996774922	13	TenZ
122	0.9347876471797457	13	Sacy
123	0.417490739720924	13	Zekken
124	1.3741247170049886	13	pANcada
125	0.694701227944486	13	johnqt
126	1.3782616685124176	13	aspas
127	0.4063442142940607	13	Less
128	1.2520083260529207	13	Saadhak
129	0.4779285562237059	13	Cauanzin
130	1.1841301364261627	13	qck
131	1.3282982705524937	14	aspas
132	1.2937247725643508	14	Less
133	1.1055728831314071	14	Saadhak
134	1.3107881015889624	14	Cauanzin
135	1.1385705502444983	14	qck
136	0.7177487332763527	14	demon1
137	1.3359722445567	14	crashies
138	1.1366065617334733	14	Ethan
139	0.2160476327466151	14	FNS
140	0.8736326929540107	14	s0m
141	0.846851875858691	15	demon1
142	0.5987346073142281	15	crashies
143	1.2178967242142333	15	Ethan
144	1.0500565630383913	15	FNS
145	0.33293576608955355	15	s0m
146	0.9039171210654315	15	keznit
147	1.1274576459463517	15	Mazino
148	0.6596238928407769	15	Shyy
149	1.1673761351244183	15	kiNgg
150	0.5913884716684288	15	tex
151	1.3936828450060852	16	keznit
152	1.2469463062663348	16	Mazino
153	0.8185228968137186	16	Shyy
154	1.069179749612533	16	kiNgg
155	1.194795070576941	16	tex
156	0.06054844951266588	16	TenZ
157	1.0295893409397094	16	Sacy
158	0.9799694048228139	16	Zekken
159	1.3437189588897198	16	pANcada
160	1.4111956789243132	16	johnqt
161	1.3865661872449404	17	TenZ
162	0.2889641981665068	17	Sacy
163	1.2318478611689727	17	Zekken
164	0.5105685869867127	17	pANcada
165	0.2478727144053561	17	johnqt
166	0.8772587305847385	17	aspas
167	1.2182807067147272	17	Less
168	1.0812268015166386	17	Saadhak
169	0.908593381819596	17	Cauanzin
170	1.3242927392325368	17	qck
171	0.9102608703424419	18	aspas
172	0.462517524451264	18	Less
173	0.11893500571882452	18	Saadhak
174	0.7218231530864028	18	Cauanzin
175	0.21539933116987825	18	qck
176	1.031257571397897	18	demon1
177	0.33546494918343217	18	crashies
178	0.5402097292029756	18	Ethan
179	0.7052460542176725	18	FNS
180	0.5325660349024165	18	s0m
181	0.6390450248520553	19	demon1
182	1.1890381687679894	19	crashies
183	0.40852519281933086	19	Ethan
184	1.3134579783554061	19	FNS
185	1.0763914850017076	19	s0m
186	0.6492160979611442	19	keznit
187	1.0302048768586323	19	Mazino
188	1.3021428855509787	19	Shyy
189	0.40538726063901137	19	kiNgg
190	0.7908317263361727	19	tex
191	0.03763327757826392	20	keznit
192	0.6136407427725474	20	Mazino
193	0.8547449893726674	20	Shyy
194	1.2019679037228346	20	kiNgg
195	0.9142934185230439	20	tex
196	1.1360263168973113	20	TenZ
197	1.0784911704314308	20	Sacy
198	1.3532518006681622	20	Zekken
199	0.998647666834042	20	pANcada
200	0.9987406149718377	20	johnqt
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 112, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 29, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 20, true);


--
-- Name: matches_matchid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.matches_matchid_seq', 1, false);


--
-- Name: valorantDatabase_playermatchrating_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."valorantDatabase_playermatchrating_id_seq"', 200, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: matches matches_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT matches_pkey PRIMARY KEY (matchid);


--
-- Name: players players_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_pkey PRIMARY KEY (playername);


--
-- Name: rounds rounds_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rounds
    ADD CONSTRAINT rounds_pkey PRIMARY KEY (matchid, roundnumber);


--
-- Name: teams teams_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_pkey PRIMARY KEY (teamname);


--
-- Name: tournaments tournaments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tournaments
    ADD CONSTRAINT tournaments_pkey PRIMARY KEY (name);


--
-- Name: valorantDatabase_playermatchrating valorantDatabase_playerm_player_id_match_id_7422d9a2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."valorantDatabase_playermatchrating"
    ADD CONSTRAINT "valorantDatabase_playerm_player_id_match_id_7422d9a2_uniq" UNIQUE (player_id, match_id);


--
-- Name: valorantDatabase_playermatchrating valorantDatabase_playermatchrating_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."valorantDatabase_playermatchrating"
    ADD CONSTRAINT "valorantDatabase_playermatchrating_pkey" PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: valorantDatabase_playermatchrating_match_id_7a8498de; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "valorantDatabase_playermatchrating_match_id_7a8498de" ON public."valorantDatabase_playermatchrating" USING btree (match_id);


--
-- Name: valorantDatabase_playermatchrating_player_id_da94e188; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "valorantDatabase_playermatchrating_player_id_da94e188" ON public."valorantDatabase_playermatchrating" USING btree (player_id);


--
-- Name: valorantDatabase_playermatchrating_player_id_da94e188_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "valorantDatabase_playermatchrating_player_id_da94e188_like" ON public."valorantDatabase_playermatchrating" USING btree (player_id varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: diffuse diffuse_diffuser_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.diffuse
    ADD CONSTRAINT diffuse_diffuser_fkey FOREIGN KEY (diffuser) REFERENCES public.players(playername);


--
-- Name: diffuse diffuse_matchid_roundnumber_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.diffuse
    ADD CONSTRAINT diffuse_matchid_roundnumber_fkey FOREIGN KEY (matchid, roundnumber) REFERENCES public.rounds(matchid, roundnumber);


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: elimination elimination_matchid_roundnumber_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.elimination
    ADD CONSTRAINT elimination_matchid_roundnumber_fkey FOREIGN KEY (matchid, roundnumber) REFERENCES public.rounds(matchid, roundnumber);


--
-- Name: elimination elimination_playereliminated_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.elimination
    ADD CONSTRAINT elimination_playereliminated_fkey FOREIGN KEY (playereliminated) REFERENCES public.players(playername);


--
-- Name: elimination elimination_playereliminating_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.elimination
    ADD CONSTRAINT elimination_playereliminating_fkey FOREIGN KEY (playereliminating) REFERENCES public.players(playername);


--
-- Name: matches matches_team1_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT matches_team1_fkey FOREIGN KEY (team1) REFERENCES public.teams(teamname) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: matches matches_team2_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT matches_team2_fkey FOREIGN KEY (team2) REFERENCES public.teams(teamname) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: matches matches_tournamentname_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT matches_tournamentname_fkey FOREIGN KEY (tournamentname) REFERENCES public.tournaments(name);


--
-- Name: plant plant_matchid_roundnumber_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plant
    ADD CONSTRAINT plant_matchid_roundnumber_fkey FOREIGN KEY (matchid, roundnumber) REFERENCES public.rounds(matchid, roundnumber);


--
-- Name: plant plant_planter_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plant
    ADD CONSTRAINT plant_planter_fkey FOREIGN KEY (planter) REFERENCES public.players(playername);


--
-- Name: players players_teamname_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_teamname_fkey FOREIGN KEY (teamname) REFERENCES public.teams(teamname);


--
-- Name: playersocialmedia playersocialmedia_playername_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.playersocialmedia
    ADD CONSTRAINT playersocialmedia_playername_fkey FOREIGN KEY (playername) REFERENCES public.players(playername);


--
-- Name: playin playin_playername_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.playin
    ADD CONSTRAINT playin_playername_fkey FOREIGN KEY (playername) REFERENCES public.players(playername);


--
-- Name: playin playin_teamname_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.playin
    ADD CONSTRAINT playin_teamname_fkey FOREIGN KEY (teamname) REFERENCES public.teams(teamname);


--
-- Name: playin playin_tournamentname_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.playin
    ADD CONSTRAINT playin_tournamentname_fkey FOREIGN KEY (tournamentname) REFERENCES public.tournaments(name);


--
-- Name: rounds rounds_matchid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rounds
    ADD CONSTRAINT rounds_matchid_fkey FOREIGN KEY (matchid) REFERENCES public.matches(matchid);


--
-- Name: teamsocialmedia teamsocialmedia_teamname_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teamsocialmedia
    ADD CONSTRAINT teamsocialmedia_teamname_fkey FOREIGN KEY (teamname) REFERENCES public.teams(teamname);


--
-- Name: valorantDatabase_playermatchrating valorantDatabase_pla_match_id_7a8498de_fk_matches_m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."valorantDatabase_playermatchrating"
    ADD CONSTRAINT "valorantDatabase_pla_match_id_7a8498de_fk_matches_m" FOREIGN KEY (match_id) REFERENCES public.matches(matchid) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: valorantDatabase_playermatchrating valorantDatabase_pla_player_id_da94e188_fk_players_p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."valorantDatabase_playermatchrating"
    ADD CONSTRAINT "valorantDatabase_pla_player_id_da94e188_fk_players_p" FOREIGN KEY (player_id) REFERENCES public.players(playername) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

