# Generated by Django 5.2 on 2025-05-02 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valorantDatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMatchRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valorantDatabase.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valorantDatabase.player')),
            ],
            options={
                'unique_together': {('player', 'match')},
            },
        ),
    ]
